# This is a basic workflow to help you get started with Actions

name: Executando meu primeiro GitHub Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: Step 1
      uses: actions/checkout@v4
      
    - name: Step 2
      run: echo "Olá, mundo! Esta é o nosso primeiro job no GitHub Actions"
    - name: Step 3
      run: echo "Olá, mundo! Este e o step 3"
    - name: Step 4
      run: echo "Olá, mundo! Este e o step 4"
